version: "2"
services:
  elasticsearch:
    image: elasticsearch:2
    command: [
      -Des.script.inline=on,
      -Des.cluster.name=hive,
      -Des.threadpool.index.queue_size=100000,
      -Des.threadpool.search.queue_size=100000,
      -Des.threadpool.bulk.queue_size=1000]
  cortex:
    image: certbdf/cortex:latest
    ports:
      - "0.0.0.0:9001:9000"
  thehive:
    image: certbdf/thehive:latest
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"